language: python
python:
- '3.6'
notifications:
  email: false
env:
  global:
  - PYPI_USR=release_bot
  - secure: "fJz1wbn+ck0bWntGyijlNbgiBXR45YUYIIgN7ToqLJRewETVWzrdjSax+Toi1YpduITShgsd3qyUhQdFxZPeOpZXtG9V91YVODloYQVbVUcSArz94MKzHwjrkV5yxXeEpwaU1OPW4ufQM280ZJWSLOy3sUXnTwOGE2tRdP1cqIV//KM8RoVoo5L4OXudDR/yH6Fq5Ksdi5z0TvBJiNduQ57dUr2RVp2FwDIxoUwExgEYbFCZikG0sav95Zhm4E/WCvIkVycrT2hJhURwsAe1mf8KzgNI2wz4Rt4ROd2kj/+UvDMRa1PnXDPrc+uFaDf857DmBmJHj+CMv2lhvoc+kUge9uEoPp5J4sul/GQbbPs4EyVLLj7WJ1Jr5yGcMU/nHSa5T6ts5Abo3IXPmyP3HmTsd8Zl2Z4eVUe9H2E3TKp+7NgLv7WxoNPfCJuQP/hZt6pmKBeGJOLV2z69gEGigE9fB8YHLrjarS4Po0HzQ/j1nwRo74hHEevMk5Y8Xs9pNB84jG5tiqCKSs4Ajt/l6As2Q+z2yYCn614D0PJj+iqpfxjconlIk2dLbvb7+MPlojCmPzyhQfKZp7Q72eMEX8Eti51VK47YxbDzwqlVq1ZDj6GSpgMU57MgFdQ2TW0apolr5GZ+Nsgm8gM3t/tv+WlVqn0o6v2hJfy58wthQt4="
  matrix:
  - TEST="PYTEST"
  - TEST="FLAKE8"
install:
# qpimage development version
- travis_retry pip install git+git://github.com/RI-Imaging/qpimage.git
# everything else
- travis_retry pip install .
# coverage packages
- travis_retry pip install flake8
- travis_retry pip install codecov coverage
- travis_retry pip install twine
- pip freeze
script:
- if [ "${TEST}" == "PYTEST" ]; then
       coverage run --source=qpsphere ./setup.py test;
       coverage report -m;
       codecov;
  else
       flake8 qpsphere;
       flake8 examples;
       flake8 tests;
  fi;
after_success:
# do not use the travis deploy service, because we need to give the
# wheel a specific platform name.
- echo "[pypi]" > $HOME/.pypirc
- echo "username: $PYPI_USR" >> $HOME/.pypirc
- echo "password: $PYPI_PWD" >> $HOME/.pypirc
- if [ "${TRAVIS_BRANCH}" == "${TRAVIS_TAG}" ] && [ "${TEST}" == "PYTEST" ]; then
       python setup.py bdist_wheel --plat-name manylinux1_x86_64;
       twine upload ./dist/*.whl;
  fi;

