clone_depth: 256
build: off
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - python --version

  # Install dependencies
  - appveyor-retry pip install git+git://github.com/RI-Imaging/qpimage.git
  - appveyor-retry pip install .

  # coverage packages
  - appveyor-retry pip install flake8
  - appveyor-retry pip install pytest codecov coverage

  # Show the installed packages
  - pip freeze

test_script:
  - coverage run --source=qpsphere setup.py test
  - coverage report -m
  - codecov

