name: Release to PyPI

on:  
  push:
    tags:
      - '*'

jobs:
  deploy:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        pip install -e .
    - name: Build and publish (Linux)
      if: runner.os == 'Linux'
      env:
        TWINE_USERNAME: ci_qpi
        TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
      run: |
        # give the wheel a specific platform name for linux
        python setup.py bdist_wheel --plat-name manylinux1_x86_64
        python setup.py sdist
        twine upload --skip-existing dist/*
    - name: Build and publish (Windows)
      if: runner.os == 'Windows'
      env:
        TWINE_USERNAME: ci_qpi
        TWINE_PASSWORD: ${{ secrets.PYPI_PWD }}
      run: |
        # platform name for Windows
        python setup.py bdist_wheel --plat-name win_amd64
        twine upload --skip-existing dist/*
